import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Button } from '@material-ui/core';
import { useTheme } from '@material-ui/core/styles';
import { makeStyles } from '@material-ui/core/styles';
import Box from '@material-ui/core/Box';
import Container from '@material-ui/core/Container';
import Grid from '@material-ui/core/Grid';
import Paper from '@material-ui/core/Paper';

const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
  },
  paper: {
    padding: theme.spacing(2),
    textAlign: 'center',
    color: theme.palette.text.secondary,
    flexDirection: 'row',
  },
}));

const styl = makeStyles((theme) => ({
  custom: {
    padding: theme.spacing(2),
    textAlign: 'center',
    color: theme.palette.text.secondary,
    flexDirection: 'column',
  },
  button: {
    background: theme.palette.primary,
  },
  customFlex: {
    flexDirection: "flex-end", 
    justifyContent: "space-around", 
    background: "red"
  }

}));

const Layout = () => {
  const classes = useStyles();
  const styles = styl()
  console.log("styles", styles)
  return (
    <>
      <Grid container spacing={3} className={styles.customFlex}>
        <Grid item xs={12}>
          <Paper className={classes.paper}>xs=12

          </Paper>
        </Grid>

        <Grid item xs={6}  >
          <Paper className={classes.paper} >
            <Container display="flex"   >

              <Button  className={styles.button}customcolor="primary">Hello World</Button>
              <Button color="primary">Hello World</Button>
              <Button color="primary">Hello World</Button>

            </Container>

          </Paper>
        </Grid>

        <Grid item xs={6}>
          <Paper className={classes.paper}>
            xs=6
          </Paper>
        </Grid>

        <Grid item xs={3}>
          <Paper className={classes.paper}
          >xs=3
          </Paper>
        </Grid>

        <Grid item xs={3}>
          <Paper className={classes.paper}>
            xs=3
          </Paper>
        </Grid>

        <Grid item xs={3}>
          <Paper className={classes.paper}>
            xs=3
          </Paper>
        </Grid>

        <Grid item xs={3}>
          <Paper className={classes.paper}>
            xs=3
          </Paper>
        </Grid>

      </Grid>
    </>
  )
}
export default function Home() {

  const theme = useTheme();
  console.log("theme", theme)


  return (
    <Box>
      <Container >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta
            name="viewport"
            content="minimum-scale=1, initial-scale=1, width=device-width"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Button color="primary">Hello World</Button>
          <Button variant="contained" color="primary">
            Hello World
          </Button>
          <Layout />
        </main>


        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </Container>
    </Box>
  )
}
